image: Visual Studio 2017
version: 2.1.0-preview2-{build}
services:
  - postgresql101
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    Test__Npgsql__DefaultConnection: Host=localhost;Database=postgres;Username=postgres;Password=Password12!
    PGUSER: postgres
    PGPASSWORD: Password12!
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
clone_depth: 10
install:
  - powershell .build\setup_appveyor.ps1
  - ps: $env:padded_build_number = $env:appveyor_build_number.PadLeft(5, '0')
  # Install .NET Core 2.0
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile "install-dotnet.ps1"
  - ps: .\install-dotnet.ps1 -Version 2.1.4
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
  - dotnet --info
  - appveyor-retry dotnet restore -v Minimal
build_script:
  - dotnet pack src\EFCore.PG\EFCore.PG.csproj -c Release --version-suffix ci-%PADDED_BUILD_NUMBER%
test_script:
  - dotnet test test\EFCore.PG.Tests\EFCore.PG.Tests.csproj -f net461
  - dotnet test test\EFCore.PG.FunctionalTests\EFCore.PG.FunctionalTests.csproj -f net461
artifacts:
  - path: 'src\**\*.nupkg'
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/npgsql-unstable/api/v2/package
    api_key:
      secure: kiMn9uBvgMa5EtEmTIhNBFUfyatiATnhkgx5Xj/1EsmKTtEkUv+hJAQs0L3VGzPw
    artifact: /.*\.nupkg/
    skip_symbols: true
    #skip_symbols: false
    #symbol_server: https://your.symbol.server/feed

